name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *" # setiap hari jam 4 pagi UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          persist-credentials: false  # 🔑 penting, biar gak pake github-actions[bot]

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Configure pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt

      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: Faizpi
        run: python today.py

      - name: Commit and push changes
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "✅ Pakai PAT untuk push"
          git config --global user.email "faizpi-bot@users.noreply.github.com"
          git config --global user.name "Faizpi-Bot"
          git remote set-url origin https://x-access-token:${ACCESS_TOKEN}@github.com/${{ github.repository }}
          git add .
          git commit -m "Updated README" -a || echo "No changes to commit"
          git pull --rebase origin main   # ⬅️ sync dulu biar ga konflik
          git push origin HEAD:main

